version: '3.9'
services:
  app_proxy:
      environment:
        APP_HOST: $APP_NOSTR_IP
        APP_PORT: $APP_NOSTR_PORT
  relay: 
    image: akbarworld/nostr-rs-relay:arm64 
    volumes:
      - ${APP_DATA_DIR}/config.toml,target=/usr/src/app/config.toml
    expose:
      - $APP_NOSTR_PORT
    ports:
      - $APP_NOSTR_PORT:8080
    networks:
      default:
        ipv4_address: $APP_NOSTR_IP

  # monitor: 
  #   image: akbarworld/nostr-watch:arm64
  #   ports:
  #     - $APP_NOSTR_WATCH_PORT:80 
  #   networks:
  #     default:
  #       ipv4_address: $APP_NOSTR_WATCH_IP

  astral: 
    image: akbarworld/astral:arm64
    ports:
      - $APP_ASTRAL_PORT:8000 
    networks:
      default:
        ipv4_address: $APP_ASTRAL_IP
volumes:
  relay-db: {}

